sudo: false
language: ruby
notifications:
  email: false

before_install:
  - gem update --system
  - gem install bundler -v '< 2'

matrix:
  fast_finish: true
  include:
    - rvm: ruby-head
      gemfile: gemfiles/railsmaster.gemfile
    - rvm: jruby-9.2.0.0
      gemfile: gemfiles/jruby.gemfile
    - rvm: 2.5.3
      gemfile: Gemfile
    - rvm: 2.4.3
      gemfile: gemfiles/rails42.gemfile
  allow_failures:
    - rvm: ruby-head
      gemfile: gemfiles/railsmaster.gemfile
    - rvm: jruby-9.2.0.0
      gemfile: gemfiles/jruby.gemfile
