name: Build

on:
  push:
    branches:
    - master
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3
      CI: true
    strategy:
      fail-fast: false
      matrix:
        ruby: ["2.7"]
        bundler: ["2"]
        gemfile: [
          "gemfiles/rails6.gemfile"
        ]
        include:
        - ruby: "3.0"
          gemfile: "gemfiles/rails6.gemfile"
        - ruby: "3.1"
          gemfile: "gemfiles/rails7.gemfile"
        - ruby: "3.2"
          gemfile: "gemfiles/rails7.gemfile"
        - ruby: "3.1"
          gemfile: "gemfiles/railsmaster.gemfile"
        - ruby: "2.6"
          gemfile: "gemfiles/rails6.gemfile"
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: /home/runner/bundle
        key: bundle-${{ matrix.ruby }}-${{ matrix.gemfile }}-${{ hashFiles(matrix.gemfile) }}-${{ hashFiles('**/*.gemspec') }}
        restore-keys: |
          bundle-${{ matrix.ruby }}-${{ matrix.gemfile }}-
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Bundle install
      run: |
        bundle config path /home/runner/bundle
        bundle config --global gemfile ${{ matrix.gemfile }}
        bundle install
        bundle update
    - name: Run Ruby Next
      run: bundle exec rake nextify
    - name: Run Minitest tests
      run: |
        bundle exec rake test
    - name: Run RSpec tests
      run: |
        bundle exec rspec --force-color
    - name: Run Minitest tests in isolation
      run: |
        bundle exec rake test:isolated

